algorithm:
  name: "nsga2"
  parameters:
    objectives: 
      - "min_bins"
      - "max_stability"
      - "min_center_of_gravity"
    crowding_dist_weight: 1.0

problem:
  bin_dimensions: [100, 100, 100]
