algorithm:
  name: "pso"
  parameters:
    inertia_weight: 0.8   # 0.7 - 0.9 (w)
    c1: 2.0               # Cognitive (pbest)
    c2: 2.0               # Social (gbest)

problem:
  bin_dimensions: [100, 100, 100]
